# Generated by Django 3.2.7 on 2021-09-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_numbers',
            new_name='phone_number',
        ),
    ]
